version: '3'

services:
  web:
    container_name: web-akrut-local
    build:
      context: ./app
    networks:
      - akrut-local
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
      - web-static-local:/usr/src/app/static
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    comand: bash -c "python manage.py makemigration &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:1234"

  nginx:
    container_name: nginx-akrut-local
    image: nginx:latest
    depends_on:
      - web
    ports:
      - ${NGINX_PORT:-8000}:9000
    volumes:
      - web-static-local:/usr/src/app/static
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - akrut-local

  db:
    container_name: db-akrut-local
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-akrut-local:/var/lib/postgresql/data/
    ports:
      - ${LOCAL_POSTGRES_PORT:-5432}:5432
    networks:
      - akrut-local

  volumes:
    web-static-local:
    db-akrut-local:

  networks:
    akrut-local:
      driver: bridge